export const WORKSHOP_OPERATION_NAMES = {
  PARTICIPANT_BUY_IMPROVEMENT: 'PARTICIPANT_BUY_IMPROVEMENT',
  PARTICIPANT_PURCHASE_ASSET: 'PARTICIPANT_PURCHASE_ASSET',
  MENTOR_APPROVE_LEVEL: 'MENTOR_APPROVE_LEVEL',
  PARTICIPANT_PROPOSE_SOCIETY: 'PARTICIPANT_PROPOSE_SOCIETY',
  PARTICIPANT_ACCEPT_SOCIETY: 'PARTICIPANT_ACCEPT_SOCIETY'
};